version: '3'
services:
  cihistory:
    image: "chrismeyers/cihistory:latest"
    working_dir: "/devel"
    volumes:
      - "../:/devel"
    ports:
      - "3000:3000"
    links:
      - mongo
      - webpack
  webpack:
    image: "chrismeyers/cihistory-webpack:latest"
    working_dir: "/devel"
    volumes:
      - "../ui:/devel"
    ports:
      - "3001:3001"
    command: "make dev"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"

